server:
   port: 8081
   
spring:
   datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/twitter
      username: postgres
      password: postgres
      maxActive: 10
      maxIdle: 5
      minIdle: 2
      initialsize: 5
      
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
      hibernate:
         ddl-auto: create